import React, { useEffect, useMemo, useState } from 'react';
import { ArrowUpRight, FileText, Users, WalletCards, Clock3, Plus, Upload, Settings2 } from 'lucide-react';
import { ClientServiceAPI, FacturationServiceAPI } from '../services/api';
import { Client, Facturation } from '../types/facturation';

interface Props { idEntreprise: string; onNavigate: (page: 'facturations'|'clients'|'import'|'parametres') => void; onOpenFacturation: (id: string) => void; }
const mois = ['Jan','Fév','Mar','Avr','Mai','Juin','Juil','Août','Sep','Oct','Nov','Déc'];
const money=(n:number)=>n.toLocaleString('fr-FR',{maximumFractionDigits:0});
export const Dashboard:React.FC<Props>=({idEntreprise,onNavigate,onOpenFacturation})=>{
 const [factures,setFactures]=useState<Facturation[]>([]); const [clients,setClients]=useState<Client[]>([]); const [loading,setLoading]=useState(true);
 useEffect(()=>{Promise.all([FacturationServiceAPI.listerFacturations(idEntreprise),ClientServiceAPI.getListeClients(idEntreprise)]).then(([f,c])=>{setFactures(f);setClients(c)}).finally(()=>setLoading(false))},[idEntreprise]);
 const valides=factures.filter(f=>f.statut==='VALIDEE').length; const brouillons=factures.filter(f=>f.statut==='BROUILLON').length;
 const points=useMemo(()=>{const now=new Date().getMonth(); return Array.from({length:6},(_,i)=>{const idx=(now-5+i+12)%12; const count=factures.filter(f=>f.mois===idx+1).length; return {label:mois[idx],value:count};})},[factures]); const max=Math.max(1,...points.map(p=>p.value));
 if(loading)return <div className="loading">Chargement du tableau de bord…</div>;
 return <>
  <div className="page-head"><div><div className="eyebrow">Vue d'ensemble</div><h1 className="page-title">Tableau de bord</h1><p className="page-desc">Pilotez vos facturations mensuelles depuis un seul espace.</p></div><div className="actions"><button className="btn btn-primary" onClick={()=>onNavigate('facturations')}><Plus size={15}/>Nouvelle facturation</button><button className="btn" onClick={()=>onNavigate('clients')}><Users size={15}/>Ajouter un client</button><button className="btn" onClick={()=>onNavigate('import')}><Upload size={15}/>Importer</button></div></div>
  <div className="grid kpi-grid">
   <div className="card kpi"><div className="kpi-top"><span className="kpi-label">Clients actifs</span><span className="kpi-icon"><Users size={16}/></span></div><div className="kpi-value">{clients.filter(c=>c.actif).length}</div><div className="kpi-meta">sur {clients.length} clients enregistrés</div></div>
   <div className="card kpi"><div className="kpi-top"><span className="kpi-label">Facturations</span><span className="kpi-icon"><FileText size={16}/></span></div><div className="kpi-value">{factures.length}</div><div className="kpi-meta">{brouillons} brouillon{brouillons!==1?'s':''}</div></div>
   <div className="card kpi"><div className="kpi-top"><span className="kpi-label">Validées</span><span className="kpi-icon"><ArrowUpRight size={16}/></span></div><div className="kpi-value">{valides}</div><div className="kpi-meta">facturations finalisées</div></div>
   <div className="card kpi"><div className="kpi-top"><span className="kpi-label">Période courante</span><span className="kpi-icon"><Clock3 size={16}/></span></div><div className="kpi-value">{mois[new Date().getMonth()]}</div><div className="kpi-meta">{new Date().getFullYear()}</div></div>
  </div>
  <div className="grid dashboard-grid">
   <section className="card section-card"><div className="section-title">Évolution des facturations</div><div className="section-sub">Nombre de périodes créées sur les 6 derniers mois</div><div className="chart"><svg viewBox="0 0 720 235" preserveAspectRatio="none"><line className="chart-grid" x1="0" y1="35" x2="720" y2="35"/><line className="chart-grid" x1="0" y1="110" x2="720" y2="110"/><line className="chart-grid" x1="0" y1="185" x2="720" y2="185"/>{points.map((p,i)=>{const x=25+i*134;const y=190-(p.value/max)*145;return <text key={p.label} className="chart-label" x={x} y={215} textAnchor="middle">{p.label}</text>})}<polyline className="chart-line" points={points.map((p,i)=>`${25+i*134},${190-(p.value/max)*145}`).join(' ')}/>{points.map((p,i)=>{const x=25+i*134;const y=190-(p.value/max)*145;return <circle key={p.label} className="chart-dot" cx={x} cy={y} r="5"/>})}</svg></div></section>
   <section className="card section-card"><div className="section-title">Actions rapides</div><div className="section-sub">Les opérations les plus utilisées</div><div className="quick-grid"><button className="quick" onClick={()=>onNavigate('facturations')}><Plus size={17} className="quick-icon"/><div className="quick-title">Créer une facturation</div><div className="quick-desc">Ouvrir un nouveau mois</div></button><button className="quick" onClick={()=>onNavigate('clients')}><Users size={17} className="quick-icon"/><div className="quick-title">Nouveau client</div><div className="quick-desc">Ajouter au registre</div></button><button className="quick" onClick={()=>onNavigate('import')}><Upload size={17} className="quick-icon"/><div className="quick-title">Importer</div><div className="quick-desc">Excel, CSV ou ODS</div></button></div><div className="alert"><Clock3 size={18}/><div><strong>Suivi des règlements</strong><div style={{fontSize:11,marginTop:3}}>Le modèle actuel gère la facturation, pas encore les paiements ou retards.</div></div></div></section>
  </div>
  <section className="card table-card" style={{marginTop:16}}><div className="table-tools"><div><div className="section-title">Facturations récentes</div><div className="section-sub">Accès direct aux dernières périodes</div></div><button className="btn" onClick={()=>onNavigate('facturations')}>Voir toutes <ArrowUpRight size={14}/></button></div><div className="table-wrap"><table className="data-table"><thead><tr><th>PÉRIODE</th><th>N° FACTURE</th><th>STATUT</th><th>ACTION</th></tr></thead><tbody>{factures.slice().sort((a,b)=>b.annee-a.annee||b.mois-a.mois).slice(0,5).map(f=><tr key={f.idFacturation}><td><strong>{mois[f.mois-1]} {f.annee}</strong></td><td>{f.numeroFacture||'—'}</td><td><span className={`status ${f.statut==='VALIDEE'?'status-valid':f.statut==='ARCHIVE'?'status-arch':'status-draft'}`}>{f.statut==='VALIDEE'?'Validée':f.statut==='ARCHIVE'?'Archivée':'Brouillon'}</span></td><td><button className="btn" onClick={()=>onOpenFacturation(f.idFacturation)}>Ouvrir</button></td></tr>)}</tbody></table></div></section>
 </>;
};
